$mainMod = SUPER
$shiftMod = SUPER SHIFT
$terminal = kitty
$fileManager = dolphin
$menu = wofi
$browser = firefox

$scripts = ~/.config/hypr/scripts

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

bind = $shiftMod, 1, movetoworkspace, 1
bind = $shiftMod, 2, movetoworkspace, 2
bind = $shiftMod, 3, movetoworkspace, 3
bind = $shiftMod, 4, movetoworkspace, 4

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, W, exec, $browser 
bind = $mainMod, E, exec, $fileManager

bind = $mainMod, H, movefocus, r
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, l

bind = $shiftMod, H, movewindow, l
bind = $shiftMod, J, movewindow, d
bind = $shiftMod, K, movewindow, u
bind = $shiftMod, L, movewindow, r

bind = $mainMod, F, fullscreen
bind = $mainMod, C, centerwindow
bind = $mainMod, X, killactive,

bind = $mainMod, space, exec, $menu
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, S, togglefloating,
bind = $mainMod, R, exec, $menu

binde = , xf86monbrightnessup,   exec, $scripts/bright+
binde = , xf86monbrightnessdown, exec, $scripts/bright-
binde = , xf86audioraisevolume,  exec, $scripts/volume+
binde = , xf86audiolowervolume,  exec, $scripts/volume-
binde = , xf86audiomute,         exec, $scripts/volumemute

input {
    kb_options = caps:super
    touchpad {
        natural_scroll = true
	scroll_factor  = 0.5
    }
}

misc {
    disable_hyprland_logo = true
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
}
