monitor = , preferred, auto, 1.5
env     = MOZ_ENABLE_WAYLAND, 1

$mainMod = SUPER
$shiftMod = SUPER SHIFT
$terminal = alacritty
$fileManager = dolphin
$menu = wofi
$browser = firefox
$gaps = 1

$scripts = ~/.config/hypr/scripts
$randwall = ~/.scripts/randwall

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

bind = $shiftMod, 1, movetoworkspace, 1
bind = $shiftMod, 2, movetoworkspace, 2
bind = $shiftMod, 3, movetoworkspace, 3
bind = $shiftMod, 4, movetoworkspace, 4

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, W, exec, $browser 
bind = $mainMod, E, exec, $fileManager

bind = $mainMod, H, movefocus, r
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, l

bind = $shiftMod, H, movewindow, l
bind = $shiftMod, J, movewindow, d
bind = $shiftMod, K, movewindow, u
bind = $shiftMod, L, movewindow, r

bind = $mainMod, F, fullscreen
bind = $mainMod, C, centerwindow
bind = $mainMod, X, killactive,

bind = $mainMod, D, exec, $scripts/togglewaybar # B but D closer
bind = $mainMod, space, exec, $menu
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, slash, togglefloating,
bind = $mainMod, R, exec, $menu

bind = $mainMod,  T, exec, $randwall # default is fit
bind = $shiftMod, T, exec, $randwall fill
bind = $shiftMod, 0, exec, $randwall fit

bind = $mainMod,  S, exec, hyprshot -m region
bind = $shiftMod, S, exec, hyprshot -m window

# "$(hyprctl getoption cursor:zoom_factor | grep float | awk '{print $2 + 1}')"
bind = $mainMod, equal, exec, hyprctl keyword cursor:zoom_factor 1.5
bind = $mainMod, minus, exec, hyprctl keyword cursor:zoom_factor 1

bind = $mainMod, V, exec, cliphist list | wofi --dmenu --pre-display-cmd "echo '%s' | cut -f 2" | cliphist decode | wl-copy

binde = , xf86monbrightnessup,   exec, $scripts/bright+
binde = , xf86monbrightnessdown, exec, $scripts/bright-
binde = , xf86audioraisevolume,  exec, $scripts/volume+
binde = , xf86audiolowervolume,  exec, $scripts/volume-
binde = , xf86audiomute,         exec, $scripts/volumemute

general {
    border_size = 0
    gaps_in  = $gaps
    gaps_out = $gaps
}

decoration {
    rounding = 0
}

input {
    kb_options = caps:super
    touchpad {
        natural_scroll = true
	scroll_factor  = 0.5
    }
}

# Tis sweet
cursor {
    inactive_timeout = 3
}

animations {
    enabled = false
}

misc {
    disable_hyprland_logo = true
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    disable_splash_rendering = true
}

exec-once = waybar
exec-once = hyprpaper
exec-once = sleep 0.5 && $randwall restore

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
