return {}
-- return {
--   'catppuccin/nvim',
--   name = 'catppuccin',
--   lazy = false,
--   priority = 1000,
--
--   config = function()
--     require('catppuccin').setup {
--       flavour = 'mocha', -- latte, frappe, macchiato, mocha
--       background = { -- :h background
--         light = 'latte',
--         dark = 'mocha',
--       },
--       transparent_background = false, -- disables setting the background color.
--       float = {
--         transparent = false, -- enable transparent floating windows
--         solid = false, -- use solid styling for floating windows, see |winborder|
--       },
--       term_colors = false, -- sets terminal colors (e.g. `g:terminal_color_0`)
--       dim_inactive = {
--         enabled = false, -- dims the background color of inactive window
--         shade = 'dark',
--         percentage = 0.15, -- percentage of the shade to apply to the inactive window
--       },
--       no_italic = false, -- Force no italic
--       no_bold = false, -- Force no bold
--       no_underline = false, -- Force no underline
--       styles = { -- Handles the styles of general hi groups (see `:h highlight-args`):
--         comments = { 'italic' }, -- Change the style of comments
--         conditionals = { 'italic' },
--         loops = {},
--         functions = { 'bold' },
--         keywords = {},
--         strings = {},
--         variables = {},
--         numbers = {},
--         booleans = {},
--         properties = {},
--         types = { 'underline' },
--         operators = {},
--         -- miscs = {}, -- Uncomment to turn off hard-coded styles
--       },
--       lsp_styles = { -- Handles the style of specific lsp hl groups (see `:h lsp-highlight`).
--         virtual_text = {
--           errors = { 'italic' },
--           hints = { 'italic' },
--           warnings = { 'italic' },
--           information = { 'italic' },
--           ok = { 'italic' },
--         },
--         underlines = {
--           errors = { 'underline' },
--           hints = { 'underline' },
--           warnings = { 'underline' },
--           information = { 'underline' },
--           ok = { 'underline' },
--         },
--         inlay_hints = {
--           background = true,
--         },
--       },
--       color_overrides = {},
--       -- custom_highlights = function(colors)
--       --   return {
--       --     MiniStatuslineModeNormal = { bg = colors.lavender, fg = colors.crust, bold = true },
--       --     FloatBorder = { fg = colors.lavender, bg = colors.mantle },
--       --   }
--       -- end,
--       default_integrations = true,
--       auto_integrations = true,
--       integrations = {
--         cmp = true,
--         gitsigns = true,
--         nvimtree = true,
--         notify = false,
--         mini = {
--           enabled = true,
--           indentscope_color = 'lavender',
--         },
--         aerial = true,
--         telescope = {
--           enabled = true,
--         },
--         which_key = true,
--         navic = {
--           enabled = true,
--           custom_bg = 'NONE', -- "lualine" will set background to mantle
--         },
--         noice = true,
--         mason = true,
--       },
--     }
--     vim.opt.termguicolors = true
--     vim.cmd.colorscheme 'catppuccin-mocha'
--   end,
-- }
