[env]
term = "xterm-256color"

[window]
decorations = "None"
opacity = 0.9
# blur = true

[window.padding]
x = 10
y = 10

[font]
size = 13.0

[font.normal]
family = "CommitMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"

[colors.primary]
background = "#090909"
