#!/bin/sh

DVR_FILE="$HOME/.scripts/.dvrmac"
DVR_ENV=$(cat $DVR_FILE)
DVR_MAC=$(echo $DVR_ENV | awk "{print \$1}")
DVR_USR=$(echo $DVR_ENV | awk "{print \$2}")
DVR_PWD=$(echo $DVR_ENV | awk "{print \$3}")

echo "Checking dvr in arp cache"
DVR_IP=$(ip neigh | grep "$DVR_MAC" | awk "{print \$1}")
if [[ "$DVR_IP" == "" ]]; then
  echo "Failed to find device in arp cache"
  echo "Fetching all devices on the network"

  IP=$(ip -4 a | grep -E "inet .* (eth0|wlan0)" | awk "{print \$2}")
  nmap -sn $IP
  DVR_IP=$(ip neigh | grep "$DVR_MAC" | awk "{print \$1}")
  if [[ "$DVR_IP" == "" ]]; then
    echo "Cannot find Device $DVR_MAC on the n/w"
    exit 1
  fi
fi
echo $DVR_MAC $DVR_IP

# ffplay -rtsp_transport tcp -an "rtsp://${DVR_USR}:${DVR_PWD}@${DVR_IP}:554/cam/playback?channel=1&starttime=2026_05_24_14_55_40&endtime=2026_05_24_14_57_00"

# vlc --rtsp-tcp --no-audio --network-caching=2000 "rtsp://${DVR_USR}:${DVR_PWD}@${DVR_IP}:554/cam/playback?channel=101&starttime=2026_05_24_14_55_40&endtime=2026_05_24_14_57_00"

# Slow to download but not bad
ffmpeg -y -rtsp_transport tcp \
  -fflags +genpts+igndts+discardcorrupt \
  -i "rtsp://${DVR_USR}:${DVR_PWD}@${DVR_IP}:554/cam/playback?channel=1&starttime=2026_05_24_14_55_40&endtime=2026_05_24_14_58_00" \
  -map 0:v \
  -vf "setpts=N/FRAME_RATE/TB" \
  -r 25 \
  -c:v libx264 -preset ultrafast -crf 23 \
  -t 140 \
  ~/fixed_footage.mp4

# ffmpeg -rtsp_transport tcp -i "rtsp://${DVR_USR}:${DVR_PWD}@${DVR_IP}:554/cam/playback?channel=101&starttime=2026_05_24_14_55_40&endtime=2026_05_24_14_58_00" -c copy -an ~/downloaded_footage.mp4

# for i in $(seq 1 3); do
#   # -fflags nobuffer -flags low_delay
#   ffplay "rtsp://${DVR_USR}:${DVR_PWD}@${DVR_IP}:554/cam/realmonitor?channel=${i}&subtype=0" &
# done

wait
