#!/bin/python

import sys

args = sys.argv[:]
for arg in args[1:]:
    if len(arg) != 6:
        print(arg + " : invalid")
        continue
    r = int("0x" + arg[0:2], 16)
    g = int("0x" + arg[2:4], 16)
    b = int("0x" + arg[4:6], 16)
    print(f"{arg} : rgb({r}, {g}, {b})")
