#!/bin/bash

WALLPAPER_DIR=~/Downloads/wallpapers
cd $WALLPAPER_DIR
count=$(ls -1 | wc -l)
rdm=$((RANDOM % (count + 1)))
FILE=$(ls -1 | sed -n "${rdm}p" | tr -d \\n)
FIT=1

if [[ $1 == "dir" ]]; then
  dolphin $WALLPAPER_DIR 2>&1 1>/dev/null &
  exit 0
elif [[ $1 == "uwu" ]]; then
  FILE="uwu-arch-linux-5k-wd.jpg"
elif [[ $1 == "vim" ]]; then
  FILE="Screenshot 2025-10-26 at 21-19-22 ³(8) Musician turned Programmer turned Musician - YouTube.png"
elif [[ $1 == "php" ]]; then
  FILE="phpgrandma.png"
  FIT=2
elif [[ $1 == "chad" ]]; then
  FILE="G8VhLwda4AIegIs.jpg"
elif [[ $1 == "archangelo" ]]; then
  FILE="lnuxangelo.jpg"
  FIT=2
elif [[ $1 == "nvim" ]]; then
  FILE="wallhaven-e87wgr.png"
elif [[ $1 == "sucks" ]]; then
  FILE="HBOBWlab0AAa0u_.jpg"
elif [[ $1 == "urbannaxal" ]]; then
  FILE="pollution-vs-police-v0-10e8tcamu83g1.webp"
  FIT=2
elif [[ $1 == "regex" ]]; then
  FILE="regex.png"
elif [[ $1 == "macroslop" ]]; then
  FILE="macroslop.webp"
elif [[ $1 == "irony" ]]; then
  FILE="irony.png"
elif [[ $1 == "terminal" ]]; then
  FILE="terminalinyourvimandviminyourterminal.jpg"
elif [[ $1 == "me" ]]; then
  FILE="Screenshot_20241225_012635.png"
  FIT=2
elif [[ $1 == "chud" ]]; then
  FILE="chud.jpg"
elif [[ $1 == "home" ]]; then
  FILE="home.jpeg"
elif [[ $1 == "consume" ]]; then
  FILE="consume.jpeg"
elif [[ $1 == "n" ]]; then
  FILE="Screenshot_20250314_164229.png"
  FIT=2
fi

echo RandWall @ $WALLPAPER_DIR
echo $FILE

if [[ $1 == "fill" ]]; then
  FIT=2
  dbus-send --session --dest=org.kde.plasmashell --type=method_call \
    /PlasmaShell org.kde.PlasmaShell.evaluateScript \
    "string:
var Desktops = desktops();
for (i = 0; i < Desktops.length; i++) {
    d = Desktops[i];
    d.wallpaperPlugin = \"org.kde.image\";
    d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");
    d.writeConfig(\"FillMode\", $FIT);
}"
  exit
elif [[ $1 == "fit" ]]; then
  dbus-send --session --dest=org.kde.plasmashell --type=method_call \
    /PlasmaShell org.kde.PlasmaShell.evaluateScript \
    "string:
var Desktops = desktops();
for (i = 0; i < Desktops.length; i++) {
    d = Desktops[i];
    d.wallpaperPlugin = \"org.kde.image\";
    d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");
    d.writeConfig(\"FillMode\", $FIT);
}"
  exit
fi

if [[ $2 == "fill" ]]; then
  FIT=2
fi

# dbus-send --session --dest=org.kde.plasmashell --type=method_call \
#   /PlasmaShell org.kde.PlasmaShell.evaluateScript "string:
# var Desktops = desktops();
# for (i=0;i<Desktops.length;i++) {
#         d = Desktops[i];
#         d.wallpaperPlugin = \"org.kde.image\";
#         d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");
#         d.writeConfig(\"Image\", \"file:///${WALLPAPER_DIR}/${FILE}\");
# }"

COLOR=$(magick $WALLPAPER_DIR/$FILE -format %c -depth 8 -scale 144x144 histogram:info:- | sort -n | tail -1 | grep -o '#......')

dbus-send --session --dest=org.kde.plasmashell --type=method_call \
  /PlasmaShell org.kde.PlasmaShell.evaluateScript "string:
var Desktops = desktops();
for (i=0;i<Desktops.length;i++) {
        d = Desktops[i];
        d.wallpaperPlugin = \"org.kde.image\";
        d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");
        d.writeConfig(\"Image\", \"file:///${WALLPAPER_DIR}/${FILE}\");
        d.writeConfig(\"FillMode\", ${FIT});
        d.writeConfig(\"Color\", \"${COLOR}\");
}"
